### ISSUE TITLE
Transifex

### ISSUE THREAD

**Issue by mentaljam** [3liz/lizmap-locales#1]
Hello and thank you for Lizmap!

Can you add localization files to [Transifex](https://www.transifex.com/)?

**Comment by rldhont** [comment]
Hi @mentaljam 

I have created a Transifex project https://www.transifex.com/3liz-1/lizmap-locales

**Comment by NvBgm** [comment]
I want to be a member off the project team to translate lizmap in Dutch.
But it does not have this Dutch in the list. 
Why ??

**Comment by rldhont** [comment]
@NvBgm Dutch was already in the list. You have been added at Dutch and Ditch (Netherlends)

**Comment by NvBgm** [comment]
Dear rldhont,

 

Translator for Dutch works again.

But translation for Dutch (Netherlands) was a mistake.

Can you remove me from there.?
 

Nico
NvBgm

 
 

Gesendet: Montag, 02. September 2019 um 16:29 Uhr
Von: "rldhont" <notifications@github.com>
An: 3liz/lizmap-locales <lizmap-locales@noreply.github.com>
Cc: Nico <nvbgm@gmx.net>, Mention <mention@noreply.github.com>
Betreff: Re: [3liz/lizmap-locales] Transifex (#1)


@NvBgm Dutch was already in the list. You have been added at Dutch and Ditch (Netherlends)

**Comment by Gustry** [comment]
@NvBgm You can remove your self from the Translation team if you don't want anymore.

I'm closing because the project is now integrated in Transifex.
