### ISSUE TITLE
Japanese translation finished 

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [3liz/lizmap-locales#11]
Nice to meet you, transifex has completed the Japanese translation. 
I would like you to convert it to a properties file once and make corrections while actually using it. 
This is my first translation, and I'm worried whether this is the way to request it. 
The text also relies on google conversion, so please kindly use English.

**Comment by Gustry** [comment]
Hi @yamamoto-ryuzo 

Thanks a lot for your contributions.
I will have a look soon to add your translations.

I hope you have translated the "master" version (next Lizmap 3.5 coming soon)

**Comment by yamamoto-ryuzo** [comment]
Hi @Gustry

Thank you very much for your question.
Looking forward to Lizmap3.5.
I will review the translation again as long as I have time until then.

**Comment by Gustry** [comment]
I keep the issue open as a reminder.

**Comment by yamamoto-ryuzo** [comment]
Hi @Gustry
Thank you for opening the issue again
In fact, I didn't know when it was right to close it.
I closed it for the time being.

**Comment by yamamoto-ryuzo** [comment]
7/22 The translation seems to be up to date.
However, the Japanese was not reflected.
Was this my procedure or something wrong?
I will check to be sure.

**Comment by Gustry** [comment]
Thanks for the feedbacks @yamamoto-ryuzo 
I just asked my colleague @laurentj to have a look.

**Comment by yamamoto-ryuzo** [comment]
Hi @Gustry
Thank you very much.

**Comment by yamamoto-ryuzo** [comment]
Hi @Gustry
I checked that the Japanese po file has been added.
I look forward to seeing it reflected in the properties of lizmap-web-client.
The people around me who are currently using Lizmap are also looking forward to the Japanese language.
Thank you very much.

**Comment by Gustry** [comment]
Done by @laurentj in e06e24be59addba6e3427423032463d30b6076b2

I think we can close this issue. Let's check the next release of Lizmap, RC 2 will be released this week.

**Comment by laurentj** [comment]
You can download unstable packages of Lizmap (3.3, 3.4, 3.5) from https://packages.3liz.org/pub/lizmap/unstable/ : they have japanese translations ;-)
