### ISSUE TITLE
Missing files for romanian translation

### ISSUE THREAD

**Issue by ygorigor** [3liz/lizmap-locales#12]
Hello.

@laurentj I translated all files to romanian language on Transifex, but in this repo some files are missing:
`action.po
dataviz.po
filter.po
`

**Comment by Gustry** [comment]
You mean 3.5.0 does not include the romanian language ?

**Comment by ygorigor** [comment]
All versions doesn't include files that I mentioned

**Comment by laurentj** [comment]
Ok, I will fix it

**Comment by ygorigor** [comment]
Ok, thanks

**Comment by laurentj** [comment]
Fixed. It was my script that retrieved from Transifex locales with the code `ro_RO` and not with the code `ro`.

Thank you for your report.
