### ISSUE TITLE
Bulgarian language translation

### ISSUE THREAD

**Issue by schwarzkrieger** [3liz/lizmap-locales#15]
Dear Sirs,
I would like to contribute in translation of this great project in Bulgarian language. I have joined Transiflex and requested Bulgarian translation, but it it not approved yet.
May I ask you to approve the language or give me additional instructions?
Thank you in advance.

**Comment by Gustry** [comment]
Hi,
I saw your request. I just wanted to double check the name of the language you requested.

Can you redo your request with `bg` and not `bg_BG` ?
Transifex doesn't allow me to change new requested languages. Sorry. Let me know if you need some help.

**Comment by schwarzkrieger** [comment]
OK, I was wondering about the plenty of Bulgarian languages there. Unlike en_GB and en_US we have only one language variant.

**Comment by Gustry** [comment]
Thanks. I think it's alright now.
Let me know if it's ok and thanks for translating.

I think you should focus on files starting with "master". THen 3.6 should be easy.
3.4 is going to be end of life very soon.
