### ISSUE TITLE
Check languages between Transifex and LWC

### ISSUE THREAD

**Issue by Gustry** [3liz/lizmap-locales#6]
Recently, Indonesian language has been added in Transifex. I just added this new language in Lizmap-plugin:
* https://github.com/3liz/lizmap-plugin/commit/654fe7e431b630605c39d7c4bfcf853dfc12b6d4
* https://github.com/3liz/lizmap-locales/commit/ee85ebc29c1adb1085d173b73f24f505f25fb21d

LWC should also be updated to reflect languages listed in https://www.transifex.com/3liz-1/lizmap-locales/languages/, especially Indonesian language (and maybe others?)

Maybe @laurentj you have an idea.

**Comment by rldhont** [comment]
Slovakian has to be added to.

Files to update :
* https://github.com/3liz/lizmap-locales/blob/master/web-client/module_list.sh
* https://github.com/3liz/lizmap-locales/blob/master/web-client/.tx/config the lang_map

**Comment by Gustry** [comment]
Files have been updated I think.
Closing
