### ISSUE TITLE
Separate jelix locales from lizmap locales

### ISSUE THREAD

**Issue by laurentj** [3liz/lizmap-locales#7]
At the beginning, we included translations for Jelix because there were only english and french translation for the Jelix framework, although Lizmap support more languages.

However, several Lizmap branches use the same version of the Jelix framework, and so, all translations for Jelix are duplicated each branches into Transifex. It has some issues:

* it takes many disk space and we almost reach the quota
* it duplicates the work of contributor on each branch
* other projects that are using Jelix does not have access easily to these translations

So we must:

* [x] create a specific project to translate strings of Jelix
* [x] modify our scripts to retrieve/push string from/to this new Tx project
* [x] modify scripts to push translated strings to lizmap and push strings  to translate to Tx
* [x] inform contributors that they have to translate into two projects (lizmap and jelix) : improve the documentation, CONTRIBUTING.md etc..
* [x] remove current translation strings of Jelix from the lizmap project of Transifex.

**Comment by laurentj** [comment]
For Jelix locales, there are now stored into a dedicated repository https://github.com/jelix/jelix-langpacks

**Comment by Gustry** [comment]
Thanks a lot @laurentj !
We will earn time in translations now !
It would be nice to know how many words we won't translate many times ;-)

I will try to update the documentation where needed.
Share here the link to transifex when it's ready.

**Comment by Gustry** [comment]
Done as well @laurentj ?
